env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12 # Equivalent to 2021
  sourceType: 'module'
  project: './config/tsconfig.json' # Specify the path to your tsconfig if you're using TypeScript
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
rules:
  indent: ['error', 2]
  quotes: ['error', 'single']
  semi: ['error', 'always']
  "@typescript-eslint/no-unused-vars": ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }]
  "react/jsx-filename-extension": [1, { "extensions": [".tsx", ".jsx"] }]
  "react/jsx-uses-react": "off"
  "react/react-in-jsx-scope": "off"
  "react-hooks/rules-of-hooks": 'error' # Checks rules of Hooks
  "react-hooks/exhaustive-deps": 'warn' # Checks effect dependencies

