repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]
      - id: pretty-format-json
        args: [--autofix]

  - repo: local
    hooks:
      - id: trunk
        name: Trunk Checks
        entry: trunk check
        language: system
        # Ensure Trunk is installed and accessible in your environment
        # This setup assumes that Trunk checks are quick enough for pre-commit

  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest version
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.32.0  # Use the version compatible with your project
    hooks:
      - id: eslint
        additional_dependencies: ['eslint@7.32.0']  # Specify ESLint version

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.2  # Use the version compatible with your project
    hooks:
      - id: prettier

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2  # Use the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.29.0  # Use the latest version
    hooks:
      - id: markdownlint

  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.54.0  # Use the latest version
    hooks:
      - id: cfn-python-lint
        files: \.(json|yml|yaml)$

  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.5.0  # Use the latest version
    hooks:
      - id: gitleaks
