name: Test Service Worker

on:
  push:
    branches:
      - main
      - preview
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: yarn install

    - name: Build the Application
      run: yarn build

    - name: Start the Application
      run: yarn start & echo "Server started" # Start the server in the background
      # Consider using a more robust way to wait for the server to start

    - name: Run Service Worker Tests
      run: npm run test:service-worker
      # This assumes you have a script defined for testing your service worker
