name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Set in your repository secrets
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }} # Also set in your repository secrets
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # Also set in your repository secrets
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
