name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Set in your repository secrets
          team-id-vercel: ${{ secrets.TEAM_ID_VERCEL }} # Set in your repository secrets
          project-id-vercel: ${{ secrets.PROJECT_ID_VERCEL }} # Set in your repository secrets
          vercel-args: '' # Add '--prod' for Production Deployments
